version: '3.7'

services:
  db:
    image: postgres
    restart: always
    networks:
      - container_net
    ports:
      - "5432:5432"
    env_file:
      - .env
    # Run sql scripts on container start
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    # Mount data volume


  server:
    build: server
    restart: always
    networks:
      - container_net
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./server:/app
    working_dir: /app

networks:
  container_net:
    driver: bridge
  