"""refresh db

Revision ID: 08028e64304d
Revises: b81143d28545
Create Date: 2022-11-20 01:48:28.460419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08028e64304d'
down_revision = 'b81143d28545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
