"""refresh db

Revision ID: 1249af9bd434
Revises: ccb6201330f2
Create Date: 2022-11-19 14:34:35.151589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1249af9bd434'
down_revision = 'ccb6201330f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
