"""refresh db

Revision ID: 137cec0f689f
Revises: 4031eb6ee04d
Create Date: 2022-11-19 00:38:14.331921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137cec0f689f'
down_revision = '4031eb6ee04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
