"""refresh db

Revision ID: 2bb2f09c61f2
Revises: 73dda4c96d04
Create Date: 2022-11-19 04:13:49.184405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb2f09c61f2'
down_revision = '73dda4c96d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_table', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_table', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
