"""refresh db

Revision ID: 2ffc3156220e
Revises: 
Create Date: 2022-11-19 09:36:24.538164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffc3156220e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('pts_hash', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('denied', sa.Boolean(), nullable=True),
    sa.Column('pts_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charging_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('types_of_charging', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('coordinates', sa.String(length=50), nullable=True),
    sa.Column('number_of_places', sa.Integer(), nullable=True),
    sa.Column('available_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charging_point_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('stars', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_of_charging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cars'], ['cars_table.id'], ),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('types_of_charging')
    op.drop_table('transactions')
    op.drop_table('reviews')
    op.drop_table('qr_table')
    op.drop_table('partners')
    op.drop_table('companies')
    op.drop_table('charging_points')
    op.drop_table('cars_table')
    # ### end Alembic commands ###
