"""refresh db

Revision ID: 4031eb6ee04d
Revises: 7304ccb1e8a5
Create Date: 2022-11-19 00:36:58.185624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4031eb6ee04d'
down_revision = '7304ccb1e8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
