"""refresh db

Revision ID: 417e6dc03a0b
Revises: 97d22134cfc7
Create Date: 2022-11-19 14:47:35.964788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417e6dc03a0b'
down_revision = '97d22134cfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('hashed_password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
