"""refresh db

Revision ID: 4d308f53d962
Revises: 1249af9bd434
Create Date: 2022-11-19 14:38:38.982011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d308f53d962'
down_revision = '1249af9bd434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
