"""refresh db

Revision ID: 7304ccb1e8a5
Revises: 84780cd3e82a
Create Date: 2022-11-18 23:49:17.664956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7304ccb1e8a5'
down_revision = '84780cd3e82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('fio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'fio')
    # ### end Alembic commands ###
