"""refresh db

Revision ID: 73dda4c96d04
Revises: e7cfa2549fa9
Create Date: 2022-11-19 04:10:47.828560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dda4c96d04'
down_revision = 'e7cfa2549fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.create_foreign_key(None, 'users_table', 'qr_table', ['qr_id'], ['id'])
    op.create_foreign_key(None, 'users_table', 'cars_table', ['cars'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.drop_constraint(None, 'users_table', type_='foreignkey')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
