"""refresh db

Revision ID: 81f49f9a42eb
Revises: 957c9b03e94f
Create Date: 2022-11-19 04:30:22.808884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f49f9a42eb'
down_revision = '957c9b03e94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
