"""refresh db

Revision ID: 84780cd3e82a
Revises: be6b0cfa8a80
Create Date: 2022-11-18 23:34:35.662736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84780cd3e82a'
down_revision = 'be6b0cfa8a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('pts_hash', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_of_charging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('qr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cars'], ['cars_table.id'], ),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('types_of_charging')
    op.drop_table('qr_table')
    op.drop_table('companies')
    op.drop_table('cars_table')
    # ### end Alembic commands ###
