"""refresh db

Revision ID: 8ba0b517373e
Revises: 2ffc3156220e
Create Date: 2022-11-19 10:06:01.432001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba0b517373e'
down_revision = '2ffc3156220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_table', sa.Column('auto_model', sa.String(), nullable=True))
    op.add_column('cars_table', sa.Column('body_color', sa.String(), nullable=True))
    op.add_column('cars_table', sa.Column('engine_type', sa.String(), nullable=True))
    op.add_column('cars_table', sa.Column('image_hash', sa.String(), nullable=True))
    op.add_column('cars_table', sa.Column('vin', sa.String(), nullable=True))
    op.drop_column('cars_table', 'denied')
    op.drop_column('cars_table', 'pts_number')
    op.drop_column('cars_table', 'verified')
    op.drop_column('cars_table', 'pts_hash')
    op.drop_column('cars_table', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_table', sa.Column('number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('pts_hash', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('pts_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('denied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('cars_table', 'vin')
    op.drop_column('cars_table', 'image_hash')
    op.drop_column('cars_table', 'engine_type')
    op.drop_column('cars_table', 'body_color')
    op.drop_column('cars_table', 'auto_model')
    # ### end Alembic commands ###
