"""empty message

Revision ID: 957c9b03e94f
Revises: d779c7039b8b
Create Date: 2022-11-19 04:17:39.490903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957c9b03e94f'
down_revision = 'd779c7039b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_table', sa.Column('denied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars_table', 'denied')
    # ### end Alembic commands ###
