"""refresh db

Revision ID: 97d22134cfc7
Revises: cdc1197685fc
Create Date: 2022-11-19 14:47:09.231037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d22134cfc7'
down_revision = 'cdc1197685fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
