"""refresh db

Revision ID: 98acc6bfce58
Revises: e891e5f632a0
Create Date: 2022-11-20 09:43:18.232480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98acc6bfce58'
down_revision = 'e891e5f632a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'company_id')
    # ### end Alembic commands ###
