"""refresh db

Revision ID: 98d2d41a6b68
Revises: 417e6dc03a0b
Create Date: 2022-11-19 14:47:42.032407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d2d41a6b68'
down_revision = '417e6dc03a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('hashed_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'hashed_password')
    # ### end Alembic commands ###
