"""refresh db

Revision ID: b869bc11c1d4
Revises: 137cec0f689f
Create Date: 2022-11-19 03:37:39.251646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b869bc11c1d4'
down_revision = '137cec0f689f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
