"""empty message

Revision ID: c9c936c5b921
Revises: f27c553557f4
Create Date: 2022-11-19 04:02:56.011329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c936c5b921'
down_revision = 'f27c553557f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_table_cars_fkey', 'users_table', type_='foreignkey')
    op.drop_constraint('users_table_qr_id_fkey', 'users_table', type_='foreignkey')
    op.drop_column('users_table', 'qr_id')
    op.drop_column('users_table', 'cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('cars', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users_table', sa.Column('qr_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_table_qr_id_fkey', 'users_table', 'qr_table', ['qr_id'], ['id'])
    op.create_foreign_key('users_table_cars_fkey', 'users_table', 'cars_table', ['cars'], ['id'])
    # ### end Alembic commands ###
