"""empty message

Revision ID: cbfcfd43307c
Revises: 81f49f9a42eb
Create Date: 2022-11-19 06:53:15.981535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbfcfd43307c'
down_revision = '81f49f9a42eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_table', sa.Column('pts_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars_table', 'pts_number')
    # ### end Alembic commands ###
