"""refresh db

Revision ID: ccb6201330f2
Revises: 8ba0b517373e
Create Date: 2022-11-19 14:25:39.223639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb6201330f2'
down_revision = '8ba0b517373e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_table', sa.Column('pts_id', sa.Integer(), nullable=True))
    op.add_column('cars_table', sa.Column('sts_id', sa.Integer(), nullable=True))
    op.add_column('cars_table', sa.Column('verified', sa.Boolean(), nullable=True))
    op.drop_column('cars_table', 'auto_model')
    op.drop_column('cars_table', 'image_hash')
    op.drop_column('cars_table', 'body_color')
    op.drop_column('cars_table', 'vin')
    op.drop_column('cars_table', 'engine_type')
    op.drop_constraint('users_table_cars_fkey', 'users_table', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_table_cars_fkey', 'users_table', 'cars_table', ['cars'], ['id'])
    op.add_column('cars_table', sa.Column('engine_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('body_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('image_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cars_table', sa.Column('auto_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cars_table', 'verified')
    op.drop_column('cars_table', 'sts_id')
    op.drop_column('cars_table', 'pts_id')
    # ### end Alembic commands ###
