"""refresh db

Revision ID: d779c7039b8b
Revises: 2bb2f09c61f2
Create Date: 2022-11-19 04:13:53.794395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd779c7039b8b'
down_revision = '2bb2f09c61f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_table', sa.Column('hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_table', 'hash')
    # ### end Alembic commands ###
