"""empty message

Revision ID: df254bb97ff3
Revises: 93cd4d735d66
Create Date: 2022-11-19 03:16:55.952263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df254bb97ff3'
down_revision = '93cd4d735d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revuews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charging_point_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('stars', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('charging_points', sa.Column('coordinates', sa.String(length=50), nullable=True))
    op.drop_column('charging_points', 'latitude')
    op.drop_column('charging_points', 'longitude')
    op.add_column('companies', sa.Column('amount', sa.FLOAT(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.String(length=50), nullable=True))
    op.add_column('users_table', sa.Column('card', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'card')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'amount')
    op.add_column('charging_points', sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('charging_points', sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('charging_points', 'coordinates')
    op.drop_table('transactions')
    op.drop_table('revuews')
    op.drop_table('partners')
    # ### end Alembic commands ###
