"""refresh db

Revision ID: e410693272db
Revises: 98d2d41a6b68
Create Date: 2022-11-19 14:50:49.214758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e410693272db'
down_revision = '98d2d41a6b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('auto_model', sa.String(), nullable=True),
    sa.Column('body_color', sa.String(), nullable=True),
    sa.Column('engine_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sts_table')
    op.drop_table('pts_table')
    # ### end Alembic commands ###
