"""refresh db

Revision ID: e60e7d195675
Revises: b869bc11c1d4
Create Date: 2022-11-19 03:39:28.806507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60e7d195675'
down_revision = 'b869bc11c1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_table', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_table', sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
