"""empty message

Revision ID: e7cfa2549fa9
Revises: c9c936c5b921
Create Date: 2022-11-19 04:03:11.605630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cfa2549fa9'
down_revision = 'c9c936c5b921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('cars', sa.Integer(), nullable=True))
    op.add_column('users_table', sa.Column('qr_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'qr_id')
    op.drop_column('users_table', 'cars')
    # ### end Alembic commands ###
