"""empty message

Revision ID: f27c553557f4
Revises: df254bb97ff3
Create Date: 2022-11-19 03:22:20.567655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f27c553557f4'
down_revision = 'df254bb97ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charging_point_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=50), nullable=True),
    sa.Column('stars', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('revuews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revuews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('charging_point_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stars', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='revuews_pkey')
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
